Authentication costam
jcebo/note_web_app pull request #7
Opened 2022-04-21 20:17 UTC by gorskik

2022-04-21 20:46 UTC, jcebo requested changes
do poprawy

2022-04-21 20:47 UTC, jcebo requested changes

2022-04-21 20:47 UTC, jcebo commented on note_app/src/views/SignIn-screen.vue
> +    <a href="/register"> czy może ;) nie masz :>>> jeszzczeee kąąątaaaa heeeee??? ;> </a>
to

2022-04-22 16:04 UTC, dborowy commented on note_app/src/views/SignIn-screen.vue
> +    <a href="/register"> czy może ;) nie masz :>>> jeszzczeee kąąątaaaa heeeee??? ;> </a>
potwierdzam

2022-04-22 22:22 UTC, merged